(defun collect ()
  (let* ((collection (cons nil nil))
         (tail collection))
    (lambda (&rest args)
      (declare (dynamic-extent args))
      (dolist (arg args (cdr collection))
        (let ((new-tail (cons arg nil)))
          (setf (cdr tail) new-tail)
          (setf tail new-tail))))))
